# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/motorola/cypfr/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    $(call find-copy-subdir-files,*,vendor/motorola/cypfr/proprietary/vendor/firmware,$(TARGET_COPY_OUT_RECOVERY)/root/vendor/firmware)
